steps:
  # Deploy App Engine Flex (serverless container)
- name: gcr.io/cloud-builders/gcloud
  args: ['app', 'deploy', '--version=tweets']
  dir: 'backend/twitter-to-pubsub'

  # Deploy Dataflow (serverless data ingestion)
- name: gcr.io/cloud-builders/gradle
  args: ['run']
  dir: 'backend/dataflow'
  waitFor: ['-']

  # Deploy Cloud function (serverless compute)
- name: "gcr.io/cloud-builders/gcloud"
  args:
    [
      "functions",
      "deploy",
      "tweets-to-firestore",
      "--entry-point",
      "PubSubConsumer",
      "--runtime",
      "go111",
      "--trigger-topic",
      "${_TWITTER_FILTERED_TOPIC}",
    ]
  dir: "backend/pubsub-to-firestore"
  waitFor: ['-']
substitutions:
  _TWITTER_FILTERED_TOPIC: tweets_filtered_beam_sql

timeout: 1800s
